#!/usr/bin/env bash

# shellcheck disable=SC2154
trap 'ret=$?; test $ret -ne 0 && printf "error\n\n" >&2; exit $ret' EXIT

set -e

if ! command -v brew >/dev/null; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

brew update --force
brew bundle --file=- <<EOF
tap "homebrew/services"

brew "openssl"

brew "autoconf" # asdf dependency
brew "automake" # asdf dependency
brew "asdf"
brew "awscli"
brew "bat"
brew "cmake"
brew "colima"
brew "coreutils"
brew "direnv"
brew "docker"
brew "docker-complete"
brew "docker-compose"
brew "exa"
brew "fzf"
brew "git"
brew "gnupg" # asdf-nodejs dependency
brew "jq"
brew "lazydocker"
brew "lazygit"
brew "less"
brew "neovim"
brew "pgcli"
brew "shellcheck"
brew "starship"
brew "stow"
brew "tmux"
brew "tree"
brew "wget"

cask "aerospace"
cask "alacritty"
cask "alfred"
cask "font-fira-code-nerd-font"
cask "google-chrome"
cask "gpg-suite-no-mail"
cask "jetbrains-gateway"
cask "jetbrains-toolbox"
cask "karabiner-elements"
cask "ngrok"
cask "rubymine"
cask "slack"
cask "spotify"
cask "whatsapp"
EOF


. "$(brew --prefix asdf)/libexec/asdf.sh"
if ! asdf plugin-list | grep -Fq "ruby"; then
  asdf plugin-add "ruby"
else
  asdf plugin-update "ruby"
fi

asdf install "$language" "ruby"
    asdf global "$language" "ruby"
gem update --system
number_cores=$(sysctl -n hw.ncpu)
bundle config --global jobs $((number_cores - 1))

gem install bundler
